// Create category
export const CATEGORY_CREATE_REQUEST = "CATEGORY_CREATE_REQUEST";
export const CATEGORY_CREATE_SUCCESS = "CATEGORY_CREATE_SUCCESS";
export const CATEGORY_CREATE_FAILURE = "CATEGORY_CREATE_FAILURE";
export const CATEGORY_CREATE_RESET = "CATEGORY_CREATE_RESET";

// List categores
export const CATEGORY_LIST_REQUEST = "CATEGORY_LIST_REQUEST";
export const CATEGORY_LIST_SUCCESS = "CATEGORY_LIST_SUCCESS";
export const CATEGORY_LIST_FAILURE = "CATEGORY_LIST_FAILURE";
export const CATEGORY_LIST_RESET = "CATEGORY_LIST_RESET";

// Get category
export const CATEGORY_GET_REQUEST = "CATEGORY_GET_REQUEST";
export const CATEGORY_GET_SUCCESS = "CATEGORY_GET_SUCCESS";
export const CATEGORY_GET_FAILURE = "CATEGORY_GET_FAILURE";
export const CATEGORY_GET_RESET = "CATEGORY_GET_RESET";

// Update category
export const CATEGORY_UPDATE_REQUEST = "CATEGORY_UPDATE_REQUEST";
export const CATEGORY_UPDATE_SUCCESS = "CATEGORY_UPDATE_SUCCESS";
export const CATEGORY_UPDATE_FAILURE = "CATEGORY_UPDATE_FAILURE";
export const CATEGORY_UPDATE_RESET = "CATEGORY_UPDATE_RESET";

// Delete category
export const CATEGORY_DELETE_REQUEST = "CATEGORY_DELETE_REQUEST";
export const CATEGORY_DELETE_SUCCESS = "CATEGORY_DELETE_SUCCESS";
export const CATEGORY_DELETE_FAILURE = "CATEGORY_DELETE_FAILURE";
export const CATEGORY_DELETE_RESET = "CATEGORY_DELETE_RESET";

// List limit categores
export const LIMIT_CATEGORY_LIST_REQUEST = "LIMIT_CATEGORY_LIST_REQUEST";
export const LIMIT_CATEGORY_LIST_SUCCESS = "LIMIT_CATEGORY_LIST_SUCCESS";
export const LIMIT_CATEGORY_LIST_FAILURE = "LIMIT_CATEGORY_LIST_FAILURE";
export const LIMIT_CATEGORY_LIST_RESET = "LIMIT_CATEGORY_LIST_RESET";
