// Create Product
export const PRODUCT_CREATE_REQUEST = "PRODUCT_CREATE_REQUEST";
export const PRODUCT_CREATE_SUCCESS = "PRODUCT_CREATE_SUCCESS";
export const PRODUCT_CREATE_FAILURE = "PRODUCT_CREATE_FAILURE";
export const PRODUCT_CREATE_RESET = "PRODUCT_CREATE_RESET";

// List Products
export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAILURE = "PRODUCT_LIST_FAILURE";
export const PRODUCT_LIST_RESET = "PRODUCT_LIST_RESET";

// Update product
export const PRODUCT_UPDATE_REQUEST = "PRODUCT_UPDATE_REQUEST";
export const PRODUCT_UPDATE_SUCCESS = "PRODUCT_UPDATE_SUCCESS";
export const PRODUCT_UPDATE_FAILURE = "PRODUCT_UPDATE_FAILURE";
export const PRODUCT_UPDATE_RESET = "PRODUCT_UPDATE_RESET";

// Delete product
export const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST";
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";
export const PRODUCT_DELETE_FAILURE = "PRODUCT_DELETE_FAILURE";
export const PRODUCT_DELETE_RESET = "PRODUCT_DELETE_RESET";

// Get product
export const PRODUCT_GET_REQUEST = "PRODUCT_GET_REQUEST";
export const PRODUCT_GET_SUCCESS = "PRODUCT_GET_SUCCESS";
export const PRODUCT_GET_FAILURE = "PRODUCT_GET_FAILURE";
export const PRODUCT_GET_RESET = "PRODUCT_GET_RESET";

//Query Products
export const PRODUCT_QUERY_REQUEST = "PRODUCT_QUERY_REQUEST";
export const PRODUCT_QUERY_SUCCESS = "PRODUCT_QUERY_SUCCESS";
export const PRODUCT_QUERY_FAILURE = "PRODUCT_QUERY_FAILURE";
export const PRODUCT_QUERY_RESET = "PRODUCT_QUERY_RESET";

//Create Product Review
export const PRODUCT_REVIEW_CREATE_REQUEST = "PRODUCT_REVIEW_CREATE_REQUEST";
export const PRODUCT_REVIEW_CREATE_SUCCESS = "PRODUCT_REVIEW_CREATE_SUCCESS";
export const PRODUCT_REVIEW_CREATE_FAILURE = "PRODUCT_REVIEW_CREATE_FAILURE";
export const PRODUCT_REVIEW_CREATE_RESET = "PRODUCT_REVIEW_CREATE_RESET";

//Product Review Permission
export const PRODUCT_REVIEW_PERMISSION_REQUEST =
  "PRODUCT_REVIEW_PERMISSION_REQUEST";
export const PRODUCT_REVIEW_PERMISSION_SUCCESS =
  "PRODUCT_REVIEW_PERMISSION_SUCCESS";
export const PRODUCT_REVIEW_PERMISSION_FAILURE =
  "PRODUCT_REVIEW_PERMISSION_FAILURE";
export const PRODUCT_REVIEW_PERMISSION_RESET =
  "PRODUCT_REVIEW_PERMISSION_RESET";

//Delete Product Review
export const PRODUCT_REVIEW_DELETE_REQUEST = "PRODUCT_REVIEW_DELETE_REQUEST";
export const PRODUCT_REVIEW_DELETE_SUCCESS = "PRODUCT_REVIEW_DELETE_SUCCESS";
export const PRODUCT_REVIEW_DELETE_FAILURE = "PRODUCT_REVIEW_DELETE_FAILURE";
export const PRODUCT_REVIEW_DELETE_RESET = "PRODUCT_REVIEW_DELETE_RESET";
